### ISSUE TITLE
S3 Source Data Buckets - AccessDenied

### ISSUE THREAD

**Issue by ndp805** [amplab/benchmark#1]
Running prepare_benchmark.sh per instructions and get "AccessDenied" on source S3 buckets and objects - specifically attempting to use the Redshift load option.  Have verified same ACL problem/symptoms by using independent S3 client against s3://big-data-benchmark/pavlo/*.  Note - I have used AWS IAM user keys which have full S3 read privileges.  Please advise - Thanks!

**Comment by pwendell** [comment]
Hey ndp,

I think we may need to explicitly open up permissions to each file/sub-directory on our end. I'll do a more thorough test of this tonight, but I just tried to do this for the redshift files:

s3://big-data-benchmark/pavlo/text

Could you check if you can access these now?

**Comment by ndp805** [comment]
Hi Patrick -

Thanks for the quick reply - unfortunately I am still getting Access Denied errors - moreover, it appears to be more restrictive because I can now no longer perform a bucket/directory listing (which was the case earlier).  I believe you should be able to leverage read-only S3 ACLs or Bucket Policies ("arn:aws:s3:::big-data-benchmark/pavlo/*") as appropriate - let me know if you'd like me to dig into this

Thanks again for all the great effort on this project
Mike

**Comment by pwendell** [comment]
Hey Mike,

Maybe you could help me actually. I spent several hours today looking at this to no avail. Because we are making these publicly available, we've turned the bucket to "reader pays" status with in S3. Based on reading a bunch of docs, my understanding is that "reader pays" disables anonymous access (for obvious reasons) and requires that all users are authenticated when they read the bucket.

To allow any authenticated users to access all of these input files, I wrote a script with boto that finds every file in the bucket and applies an ACL giving READ permissions for the AuthenticaedUser class. Here's an example ACL as applied to one of the files:

s3cmd info "s3://big-data-benchmark/pavlo/sequence/5nodes/rankings/part-00002"
s3://big-data-benchmark/pavlo/sequence/5nodes/rankings/part-00002 (object):
   File size: 64472798
   Last mod:  Wed, 08 May 2013 23:35:05 GMT
   MIME type: binary/octet-stream
   MD5 sum:   4635ae4f7d40bb15ed45298660b5cf06
   policy: none
   ACL:       pwendell+ec2: FULL_CONTROL
   ACL:       http://acs.amazonaws.com/groups/global/AuthenticatedUsers: READ

However, I noticed that S3 still sends forbidden messages if you try to access this bucket from an account that is not my own. I've used s3cmd and the Hadoop scripts to verify this. They both authenticate against s3 as far as I know.

Is there another orthogonal security policy which might be preventing access here?

What we're trying to setup is similar to the other public hosted S3 datasets.

**Comment by mateiz** [comment]
Patrick, it might need some kind of "list" permission on the bucket too. I'd recommend trying the S3 web UI on Amazon's console.

**Comment by pwendell** [comment]
No the issue is that a requestor pays bucket requires that an extra header is set on the read side. I was able to access this bucket fine from a different account using that header:

$> s3cmd ls --add-header=x-amz-request-payer:requester "s3://big-data-benchmark/pavlo/sequence/5nodes/rankings/"
2013-05-08 23:34  64460813   s3://big-data-benchmark/pavlo/sequence/5nodes/rankings/part-00000
2013-05-08 23:34  64422484   s3://big-data-benchmark/pavlo/sequence/5nodes/rankings/part-00001
2013-05-08 23:35  64472798   s3://big-data-benchmark/pavlo/sequence/5nodes/rankings/part-00002
2013-05-08 23:35  64497293   s3://big-data-benchmark/pavlo/sequence/5nodes/rankings/part-00003
2013-05-08 23:34  64437167   s3://big-data-benchmark/pavlo/sequence/5nodes/rankings/part-00004

I'm not sure if the Hadoop distcp tools support adding extra headers like that... will look into it.

**Comment by pwendell** [comment]
More info here about this requirement. We may just need to make this a normal bucket and just monitor how often it's used...

http://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html

**Comment by mateiz** [comment]
I believe Hadoop does support it; you just need to put your credentials in core-site.xml.

**Comment by pwendell** [comment]
Mike - while we figure this out, I'm disabling requester pays. Let me know if you still have trouble accessing.

**Comment by ndp805** [comment]
Great!  Thanks Patrick - I'm able to access the files now ... I'll also try to noodle on the "Requestor Pays" use case as well and will advise if I come across a possible approach ....
